// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.pm_authentication_comboBox_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.AboutBox.okButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.AboutBox.textBoxDescription_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.appintent_check_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.authentication_comboBox_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.cancel_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.ok_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.pm_appintent_check_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.pm_saveLocalSettings")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.pm_test_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.shareSettings_checkBox_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.DatabaseSelect.test_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.aboutToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.backgroundWorker1_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.backgroundWorker1_ProgressChanged(System.Object,System.ComponentModel.ProgressChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.backgroundWorker1_RunWorkerCompleted(System.Object,System.ComponentModel.RunWorkerCompletedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.btnCleanBuffer_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.btnFreeCache_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.cancel_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.database_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.exceptions_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.exitToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.go_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.loadSettingsFileDialog_FileOk(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.loadSettingsToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.mainUITimer_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.optionsToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.param_button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.saveSettingsFileDialog_FileOk(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.saveSettingsToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.toClipboardToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.toCsvToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.totalExceptions_textBox_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:SQLQueryStress.Form1.toTextToolStripMenuItem_Click(System.Object,System.EventArgs)")]
