//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLQueryStress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // (with an /str option, or as a property in the Visual Studio solution file).
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLQueryStress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set valid database connection information. Click the Database button to configure the settings..
        /// </summary>
        internal static string MustSetValidDbConnInfo {
            get {
                return ResourceManager.GetString("MustSetValidDbConnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings..
        /// </summary>
        internal static string ErrLoadingSettings {
            get {
                return ResourceManager.GetString("ErrLoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings..
        /// </summary>
        internal static string ErrorSavingSettings {
            get {
                return ResourceManager.GetString("ErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        internal static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set valid database connection information. Click the Database button to configure the settings..
        /// </summary>
        internal static string MustSetValidDatabaseConn {
            get {
                return ResourceManager.GetString("MustSetValidDatabaseConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No variables were identified in the main query. Variables must be used there before parameter substitution can be used..
        /// </summary>
        internal static string NoVarsWereIdentified {
            get {
                return ResourceManager.GetString("NoVarsWereIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Succeeded.
        /// </summary>
        internal static string ConnSucc {
            get {
                return ResourceManager.GetString("ConnSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string ConnFail {
            get {
                return ResourceManager.GetString("ConnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLQueryStress Configuration Files|*.json.
        /// </summary>
        internal static string ConfigFiles {
            get {
                return ResourceManager.GetString("ConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv Files (*.csv)|*.csv.
        /// </summary>
        internal static string CsvFiles {
            get {
                return ResourceManager.GetString("CsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to continue.
        /// </summary>
        internal static string EnterToContinue {
            get {
                return ResourceManager.GetString("EnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        internal static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlQueryStress.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLQueryStress.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.0.1.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Adam Machanic 2006.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit https://github.com/ErikEJ/SqlQueryStress for documentation and updates!.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutBox.
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect I/O Statistics.
        /// </summary>
        internal static string CollectIOStatistics {
            get {
                return ResourceManager.GetString("CollectIOStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Time Statistics.
        /// </summary>
        internal static string CollectTimeStatistics {
            get {
                return ResourceManager.GetString("CollectTimeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout.
        /// </summary>
        internal static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Timeout (0 = Unlimited).
        /// </summary>
        internal static string CommandTimeout {
            get {
                return ResourceManager.GetString("CommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Connection Pooling.
        /// </summary>
        internal static string EnableConnectionPooling {
            get {
                return ResourceManager.GetString("EnableConnectionPooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Client Retrieval of Data.
        /// </summary>
        internal static string ForceClientRetrievalData {
            get {
                return ResourceManager.GetString("ForceClientRetrievalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Queries on Cancel.
        /// </summary>
        internal static string KillQueriesOnCancel {
            get {
                return ResourceManager.GetString("KillQueriesOnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Options.
        /// </summary>
        internal static string ConnectionOptions {
            get {
                return ResourceManager.GetString("ConnectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Options.
        /// </summary>
        internal static string CommandOptions {
            get {
                return ResourceManager.GetString("CommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OptionsOK {
            get {
                return ResourceManager.GetString("OptionsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OptionsCancel {
            get {
                return ResourceManager.GetString("OptionsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string QueryLabel {
            get {
                return ResourceManager.GetString("QueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        internal static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save BenchMark.
        /// </summary>
        internal static string SaveBenchmark {
            get {
                return ResourceManager.GetString("SaveBenchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Csv.
        /// </summary>
        internal static string ToCsv {
            get {
                return ResourceManager.GetString("ToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Text.
        /// </summary>
        internal static string ToText {
            get {
                return ResourceManager.GetString("ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Clipboard.
        /// </summary>
        internal static string ToClipboard {
            get {
                return ResourceManager.GetString("ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO.
        /// </summary>
        internal static string GoButton {
            get {
                return ResourceManager.GetString("GoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Iterations.
        /// </summary>
        internal static string NumberOfIterations {
            get {
                return ResourceManager.GetString("NumberOfIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Threads.
        /// </summary>
        internal static string NumberOfThreads {
            get {
                return ResourceManager.GetString("NumberOfThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations Completed.
        /// </summary>
        internal static string IterationsCompleted {
            get {
                return ResourceManager.GetString("IterationsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Seconds/Iteration (Avg).
        /// </summary>
        internal static string ClientSecondsIteration {
            get {
                return ResourceManager.GetString("ClientSecondsIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Exceptions.
        /// </summary>
        internal static string TotalExceptions {
            get {
                return ResourceManager.GetString("TotalExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        internal static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Threads.
        /// </summary>
        internal static string ActiveThreads {
            get {
                return ResourceManager.GetString("ActiveThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ExceptionsButton {
            get {
                return ResourceManager.GetString("ExceptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Seconds/Iteration (Avg).
        /// </summary>
        internal static string CPUSecondsIteration {
            get {
                return ResourceManager.GetString("CPUSecondsIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Reads/Iteration (Avg).
        /// </summary>
        internal static string LogicalReadsIteration {
            get {
                return ResourceManager.GetString("LogicalReadsIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Seconds/Iteration (Avg).
        /// </summary>
        internal static string ActualSecondsIteration {
            get {
                return ResourceManager.GetString("ActualSecondsIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Substitution.
        /// </summary>
        internal static string ParameterSubstitution {
            get {
                return ResourceManager.GetString("ParameterSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Cache.
        /// </summary>
        internal static string FreeCache {
            get {
                return ResourceManager.GetString("FreeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Buffers.
        /// </summary>
        internal static string CleanBuffers {
            get {
                return ResourceManager.GetString("CleanBuffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between queries (ms).
        /// </summary>
        internal static string DelayBetweenQueries {
            get {
                return ResourceManager.GetString("DelayBetweenQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DatabaseSelectCancel {
            get {
                return ResourceManager.GetString("DatabaseSelectCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DatabaseSelectOK {
            get {
                return ResourceManager.GetString("DatabaseSelectOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Database.
        /// </summary>
        internal static string DefaultDatabase {
            get {
                return ResourceManager.GetString("DefaultDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Load Settings.
        /// </summary>
        internal static string MainLoadSettings {
            get {
                return ResourceManager.GetString("MainLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-refresh.
        /// </summary>
        internal static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Parameters.
        /// </summary>
        internal static string AdditionalParameters {
            get {
                return ResourceManager.GetString("AdditionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Intent.
        /// </summary>
        internal static string ApplicationIntent {
            get {
                return ResourceManager.GetString("ApplicationIntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterization Settings.
        /// </summary>
        internal static string ParameterizationSettings {
            get {
                return ResourceManager.GetString("ParameterizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Connection Settings.
        /// </summary>
        internal static string ShareConnectionSettings {
            get {
                return ResourceManager.GetString("ShareConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Server Certificate.
        /// </summary>
        internal static string TrustServerCertificate {
            get {
                return ResourceManager.GetString("TrustServerCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Query.
        /// </summary>
        internal static string ParameterQuery {
            get {
                return ResourceManager.GetString("ParameterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Columns.
        /// </summary>
        internal static string GetColumns {
            get {
                return ResourceManager.GetString("GetColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ParamWindowOK {
            get {
                return ResourceManager.GetString("ParamWindowOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ParamWindowCancel {
            get {
                return ResourceManager.GetString("ParamWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Mappings.
        /// </summary>
        internal static string ParameterMappings {
            get {
                return ResourceManager.GetString("ParameterMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string ParamWindowDatabase {
            get {
                return ResourceManager.GetString("ParamWindowDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Substitution.
        /// </summary>
        internal static string ParamWindowTitle {
            get {
                return ResourceManager.GetString("ParamWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form2.
        /// </summary>
        internal static string DataViewerTitle {
            get {
                return ResourceManager.GetString("DataViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while background threads are canceled.
        /// </summary>
        internal static string PleaseWaitCancel {
            get {
                return ResourceManager.GetString("PleaseWaitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Select.
        /// </summary>
        internal static string DatabaseSelectTitle {
            get {
                return ResourceManager.GetString("DatabaseSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string ParameterColumn {
            get {
                return ResourceManager.GetString("ParameterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datatype.
        /// </summary>
        internal static string DatatypeColumn {
            get {
                return ResourceManager.GetString("DatatypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ColumnColumn {
            get {
                return ResourceManager.GetString("ColumnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon QueryStressIcon {
            get {
                object obj = ResourceManager.GetObject("QueryStressIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
